{
 "title": "Kubernetes / Conntracker",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "prometheus_replica",
    "label": "prometheus_replica",
    "query": "label_values(up{job=\"apiserver\",prometheus_replica=~\".*k8s.*\"},prometheus_replica)"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info{prometheus_replica=\"$prometheus_replica\"}, cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(node_boot_time_seconds{cluster=\"$cluster\", job=\"node-exporter\",prometheus_replica=\"$prometheus_replica\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "conntrack-stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "node_nf_conntrack_max",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_nf_conntrack_max{node=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_count",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
     "targets": [
      {
       "expr": "node_nf_conntrack_count{node=~\"$instance\"}\n"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_current_count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_nf_conntrack_count{node=~\"$instance\"})by(node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_searched",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_searched{node=~\"$instance\"}[2m]))by(node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_found",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_found{node=~\"$instance\"}[2m]))by(node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_new",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_new{node=~\"$instance\"}[2m]))by(node)\n",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_invalid",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_invalid{node=~\"$instance\"}[2m]))by(node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_delete",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_delete{node=~\"$instance\"}[2m]))by(node)\n",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_delete_list",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_delete_list{node=~\"$instance\"}[2m]))by(node)\n",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_insert",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_insert{node=~\"$instance\"}[2m]))by(node)\n",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_insert_failed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_insert_failed{node=~\"$instance\"}[2m]))by(node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_drop",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_drop{node=~\"$instance\"}[2m]))by(node)\n",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_early_drop",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_early_drop{node=~\"$instance\"}[2m]))by(node)\n",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_icmp_error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_icmp_error{node=~\"$instance\"}[2m]))by(node)\n",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "node_nf_conntrack_stat_search_restart",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_nf_conntrack_stat_search_restart{node=~\"$instance\"}[2m]))by(node)\n",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  { "title": "conntrack-list", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "tcp_outbound_entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(node_nf_conntrack_entrylist{protocal=\"tcp\",node=~\"$instance\"})by(src))",
     "legendFormat": "{{ src }}->"
    }
   ]
  },
  {
   "title": "udp_outbound_entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(node_nf_conntrack_entrylist{protocal=\"udp\",node=~\"$instance\"})by(src))",
     "legendFormat": "{{ src }}->"
    }
   ]
  },
  {
   "title": "tcp_inbound_entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(node_nf_conntrack_entrylist{protocal=\"tcp\",node=~\"$instance\"})by(des))",
     "legendFormat": "->{{ des }}"
    }
   ]
  },
  {
   "title": "udp_inbound_entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(node_nf_conntrack_entrylist{protocal=\"udp\",node=~\"$instance\"})by(des))",
     "legendFormat": "->{{ des }}"
    }
   ]
  },
  {
   "title": "udp_inbound_and_outbound_entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(node_nf_conntrack_entrylist{protocal=\"udp\",node=~\"$instance\"})by(src,des))",
     "legendFormat": "{{ src }} <--> {{ des }}"
    }
   ]
  },
  {
   "title": "tcp_inbound_and_outbound_entries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(node_nf_conntrack_entrylist{protocal=\"tcp\",node=~\"$instance\"})by(src,des))",
     "legendFormat": "{{ src }} <--> {{ des }}"
    }
   ]
  },
  {
   "title": "TIME_WAIT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum(node_nf_conntrack_entrylist{protocal=\"tcp\",state=\"TIME_WAIT\",node=~\"$instance\"})by(src,des))",
     "legendFormat": "{{src}} <--> {{des}}"
    }
   ]
  }
 ]
}